# This is a basic workflow to help you get started with Actions

name: Deploy to Dokku

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0  
            
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: 'knyz.org'
            app-name: 'nginx-pagespeed'
