
name: Health Check
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install nginx-pagespeed
        run: |
          sudo bash install.sh
          sudo cp pagespeed.conf.sample /etc/nginx/conf.d/pagespeed.conf
        
      - name: Test configuration
        run: |
          sudo systemctl restart nginx
          sudo nginx -T
